#!/usr/bin/env python3
"""
STEP 2 - Run this AFTER fix_files.py.

Adds a floating circular Admin Dashboard button (bottom-right corner)
to every HTML report generated by write_html_report() in sprint_health_2.py.

How to use:
  cd /path/to/your/project
  python3 add_dashboard_button.py

Optional env var:
  ADMIN_DASHBOARD_URL=http://127.0.0.1:8765  (default)
"""
import os, shutil

DASHBOARD_URL = os.getenv('ADMIN_DASHBOARD_URL', 'http://127.0.0.1:8765').strip()
TARGET = 'sprint_health_2.py'

# ─── FAB CSS ──────────────────────────────────────────────────────────────────
# Injected right before the .footer rule inside write_html_report's <style> block
FAB_CSS = (
    '\n'
    '/* ─── Floating Admin Dashboard Button ─── */\n'
    '.fab-wrapper{position:fixed;bottom:28px;right:28px;z-index:9999}\n'
    '.fab-dashboard{'
        'width:56px;height:56px;border-radius:50%;'
        'background:linear-gradient(135deg,#1a6bff,#00d4aa);'
        'box-shadow:0 4px 20px rgba(26,107,255,.45),0 2px 8px rgba(0,0,0,.4);'
        'display:flex;align-items:center;justify-content:center;'
        'cursor:pointer;border:none;text-decoration:none;'
        'transition:transform .2s ease,box-shadow .2s ease}\n'
    '.fab-dashboard:hover{'
        'transform:scale(1.12) translateY(-2px);'
        'box-shadow:0 8px 28px rgba(26,107,255,.55),0 4px 12px rgba(0,0,0,.5)}\n'
    '.fab-dashboard svg{width:24px;height:24px;fill:#fff}\n'
    '.fab-tooltip{'
        'position:absolute;bottom:64px;right:0;'
        'background:rgba(10,20,40,.95);color:#e0eaff;font-size:12px;font-weight:600;'
        'padding:6px 12px;border-radius:8px;border:1px solid rgba(26,107,255,.3);'
        'pointer-events:none;opacity:0;transform:translateY(4px);'
        'transition:opacity .2s,transform .2s;white-space:nowrap}\n'
    '.fab-wrapper:hover .fab-tooltip{opacity:1;transform:translateY(0)}\n'
)

# ─── FAB HTML ─────────────────────────────────────────────────────────────────
# Injected right before the footer div inside the f-string in write_html_report
FAB_HTML = (
    '\n  <!-- Floating Admin Dashboard Button -->\n'
    '  <div class="fab-wrapper">\n'
    f'    <a href="{DASHBOARD_URL}" target="_blank" class="fab-dashboard" title="Open Admin Dashboard">\n'
    '      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">\n'
    '        <path d="M3 13h8V3H3v10zm0 8h8v-6H3v6zm10 0h8V11h-8v10zm0-18v6h8V3h-8z"/>\n'
    '      </svg>\n'
    '    </a>\n'
    '    <div class="fab-tooltip">Admin Dashboard</div>\n'
    '  </div>\n'
)

# ─── Main ─────────────────────────────────────────────────────────────────────
if not os.path.exists(TARGET):
    print(f'[error] {TARGET} not found — run this script from the project directory')
    raise SystemExit(1)

with open(TARGET, 'r', encoding='utf-8') as fh:
    src = fh.read()

# Guard: already patched?
if 'fab-dashboard' in src:
    print(f'[skip] Dashboard button already present in {TARGET}')
    raise SystemExit(0)

patched = src

# ─── Inject CSS ───────────────────────────────────────────────────────────────
# The CSS lives inside a large f-string in write_html_report.
# We look for the .footer rule which is always near the end of the style block.
CSS_ANCHORS = [
    '.footer{text-align:center;margin-top:40px;padding:20px;color:#2d5a8e;font-size:11px}',
    '.footer{text-align:center',
]
css_injected = False
for anchor in CSS_ANCHORS:
    if anchor in patched:
        patched = patched.replace(anchor, FAB_CSS + anchor, 1)
        print(f'[ok] FAB CSS injected (anchor: {anchor[:40]}...)')
        css_injected = True
        break

if not css_injected:
    print('[warn] Could not find CSS anchor — CSS not injected. Add FAB_CSS manually before .footer rule.')

# ─── Inject HTML ──────────────────────────────────────────────────────────────
HTML_ANCHORS = [
    '  <div class="footer">Lumofy QA | Sprint Health Dashboard |',
    '  <div class="footer">',
]
html_injected = False
for anchor in HTML_ANCHORS:
    if anchor in patched:
        patched = patched.replace(anchor, FAB_HTML + anchor, 1)
        print(f'[ok] FAB HTML injected (anchor: {anchor[:50]}...)')
        html_injected = True
        break

if not html_injected:
    print('[warn] Could not find HTML anchor — HTML not injected. Add FAB_HTML manually before .footer div.')

# ─── Save ─────────────────────────────────────────────────────────────────────
if css_injected or html_injected:
    backup = TARGET + '.pre_fab.bak'
    shutil.copy(TARGET, backup)
    with open(TARGET, 'w', encoding='utf-8') as fh:
        fh.write(patched)
    print(f'[saved] {TARGET}')
    print(f'[backup] {backup}')
    print(f'\nDashboard URL: {DASHBOARD_URL}')
    print('The floating button will appear on every generated report.')
else:
    print('[error] Nothing was patched.')

print('\nAll done!')